name: dupcheck

on: [ push, pull_request ]

jobs:
  dupcheck:
    runs-on: ubuntu-latest
    if: github.event.head_commit.author.email != 'action@github.com'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Check
        run: bash scripts/dupcheck.bash
